# Generated by Django 2.0.1 on 2018-01-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180118_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
