# Generated by Django 2.0.1 on 2018-01-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bargains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargain',
            name='bargain_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bargains.BargainType'),
        ),
    ]
